// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetSentry.Server.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NetSentry.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NetSentry.Server.Models.Disk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DriveName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("FreeSizeGb")
                        .HasColumnType("double precision");

                    b.Property<int>("MachineId")
                        .HasColumnType("integer");

                    b.Property<double>("TotalSizeGb")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.ToTable("Disks");
                });

            modelBuilder.Entity("NetSentry.Server.Models.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CpuName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FirstConnected")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GpuName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastConnected")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OsVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("NetSentry.Server.Models.Metric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("CpuUsage")
                        .HasColumnType("real");

                    b.Property<int>("MachineId")
                        .HasColumnType("integer");

                    b.Property<float>("RamFree")
                        .HasColumnType("real");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.ToTable("Metrics");
                });

            modelBuilder.Entity("NetSentry.Server.Models.Disk", b =>
                {
                    b.HasOne("NetSentry.Server.Models.Machine", "Machine")
                        .WithMany("Disks")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("NetSentry.Server.Models.Metric", b =>
                {
                    b.HasOne("NetSentry.Server.Models.Machine", "Machine")
                        .WithMany("Metrics")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("NetSentry.Server.Models.Machine", b =>
                {
                    b.Navigation("Disks");

                    b.Navigation("Metrics");
                });
#pragma warning restore 612, 618
        }
    }
}
